spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first_project?createDatabaseIfNotExist=true
    username: root
    password: Shihab14032001
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 3600 # 1 hour
    refreshTokenExpiration: 604800 # 7 days